Repository uiowahjmjohnsonselt2023/selt2023-final-project-team-001, pull requests merged in 2023-11, with the labels that each got.

#3 docs: add installation instructions for PostgreSQL on Ubuntu to README
  README.md
Labels: documentation

#7 Fix from my incorrect pull request merge conflict resolution
  Gemfile.lock
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/schema.rb
  db/seeds.rb
Labels: bug

#15 Product create and edit routes
  app/controllers/products_controller.rb
  app/helpers/products_helper.rb
  app/views/products/_form.html.erb
  app/views/products/edit.html.erb
  app/views/products/index.html.erb
  app/views/products/new.html.erb
  app/views/products/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/controllers/products_controller_spec.rb
  spec/factories/products.rb
  spec/factories/users.rb
  spec/helpers/products_helper_spec.rb
  spec/models/product_spec.rb
  spec/rails_helper.rb
  spec/requests/products_spec.rb
  spec/support/helpers.rb
  spec/views/products/edit.html.erb_spec.rb
  spec/views/products/new.html.erb_spec.rb
  spec/views/products/show.html.erb_spec.rb
Labels: enhancement

#16 User Profile
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/home_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/profiles_helper.rb
  app/models/profile.rb
  app/models/user.rb
  app/uploaders/avatar_uploader.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/profiles/delete.html.erb
  app/views/profiles/edit.html.erb
  app/views/profiles/new.html.erb
  app/views/profiles/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20231109201942_create_profiles.rb
  db/migrate/20231110040315_add_avatar_to_profiles.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/development.rb
  spec/controllers/profiles_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/factories/profiles.rb
  spec/factories/users.rb
  spec/fixtures/files/test-avatar.png
  spec/helpers/profiles_helper_spec.rb
  spec/models/profile_spec.rb
  spec/requests/profiles_spec.rb
Labels: enhancement

#22 Fix Heroku faker bug and add dummy profiles to seeds
  db/seeds.rb
  db/seeds/development.rb
Labels: bug

#23 fix: problem with email top level domains
  app/models/user.rb
  db/seeds/development.rb
Labels: bug

#24 Update look of the website
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/images/icons/alert-triangle.svg
  app/assets/images/icons/check-circle-2.svg
  app/assets/images/icons/info.svg
  app/assets/images/icons/shopping-cart.svg
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/controllers/products_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/flash_helper.rb
  app/helpers/footer_helper.rb
  app/helpers/icon_helper.rb
  app/helpers/navbar_helper.rb
  app/javascript/application.js
  app/javascript/controllers/application.js
  app/javascript/controllers/index.js
  app/models/current.rb
  app/models/user.rb
  app/views/application/_alert.html.erb
  app/views/application/_footer.html.erb
  app/views/application/_navbar.html.erb
  app/views/application/navbar/_user_dropdown.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/products/index.html.erb
  app/views/sessions/new.html.erb
  app/views/users/new.html.erb
  bin/importmap
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/inline_svg.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/controllers/sessions_controller_spec.rb
  spec/models/user_spec.rb
  spec/requests/sessions_spec.rb
  vendor/javascript/.keep
Labels: enhancement

#25 Remove unused views and actions
  app/controllers/users_controller.rb
  app/views/users/create.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
Labels: bug

#28 Make custom error pages
  app/controllers/errors_controller.rb
  app/controllers/products_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/users_controller.rb
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  config/application.rb
  config/environments/development.rb
  config/routes.rb
  public/404.html
  public/500.html
  spec/controllers/products_controller_spec.rb
  spec/controllers/profiles_controller_spec.rb
Labels: enhancement

#26 Refactor require_login to allow displaying flash alerts
  app/controllers/application_controller.rb
  app/controllers/checkouts_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/views/profiles/show.html.erb
  app/views/users/register.html.erb
  config/locales/en.yml
  config/routes.rb
  db/schema.rb
  spec/controllers/profiles_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: enhancement

#37 fix: remove unneeded html
  app/views/products/index.html.erb
Labels: bug

#36 Quick bug fixes
  app/controllers/products_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  db/seeds.rb
  spec/models/product_spec.rb
Labels: bug

#38 refactor: simplify products index with scopes
  Gemfile.lock
  app/controllers/products_controller.rb
  app/models/product.rb
Labels: enhancement

#31 Storefront
  Gemfile.lock
  app/assets/images/carousel/template1.jpg
  app/assets/images/carousel/template2.jpg
  app/assets/javascripts/checkouts.js
  app/assets/stylesheets/application.scss
  app/controllers/home_controller.rb
  app/controllers/storefronts_controller.rb
  app/helpers/storefront_helper.rb
  app/models/storefront.rb
  app/models/user.rb
  app/views/application/navbar/_user_dropdown.html.erb
  app/views/home/index.html.erb
  app/views/profiles/show.html.erb
  app/views/storefronts/_custom_code_output.html.erb
  app/views/storefronts/new.html.erb
  app/views/storefronts/new_storefront_with_template.html.erb
  app/views/storefronts/show.html.erb
  app/views/storefronts/template1.html.erb
  app/views/storefronts/template2.html.erb
  config/locales/en.yml
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20231117052029_create_storefronts.rb
  db/schema.rb
  db/seeds/development.rb
  spec/controllers/storefronts_controller_spec.rb
  spec/factories/storefronts.rb
  spec/helpers/storefront_helper_spec.rb
  spec/models/storefront_spec.rb
  spec/requests/storefronts_spec.rb
  spec/views/storefronts/new.html.erb_spec.rb
Labels: enhancement

#35 Add searching for products
  Gemfile
  Gemfile.lock
  app/controllers/products_controller.rb
  app/helpers/products_helper.rb
  app/models/product.rb
  app/views/application/_navbar.html.erb
  app/views/products/index.html.erb
  config/application.rb
  db/migrate/20231124045627_add_searchable_column_to_products.rb
  db/migrate/20231124050558_add_index_to_searchable_products.rb
  db/seeds/search.rb
  db/structure.sql
  spec/controllers/products_controller_spec.rb
Labels: enhancement

#34 Detailed product page
  Gemfile.lock
  app/assets/images/fallbacks/products/main_default.png
  app/assets/images/fallbacks/products/thumb_default.png
  app/assets/images/icons/more-horizontal.svg
  app/assets/images/icons/star-fill.svg
  app/assets/images/icons/star-half-fill.svg
  app/assets/images/icons/star.svg
  app/assets/stylesheets/application.scss
  app/controllers/carts_controller.rb
  app/controllers/products_controller.rb
  app/helpers/ratings_helper.rb
  app/models/cart.rb
  app/models/product.rb
  app/uploaders/product_photo_uploader.rb
  app/views/application/_rating_stars.html.erb
  app/views/application/navbar/_user_dropdown.html.erb
  app/views/products/_form.html.erb
  app/views/products/listing/_categories.html.erb
  app/views/products/listing/_condition.html.erb
  app/views/products/listing/_payment.html.erb
  app/views/products/listing/_quantity_input.html.erb
  app/views/products/listing/_seller_dropdown.html.erb
  app/views/products/listing/_seller_info.html.erb
  app/views/products/show.html.erb
  config/initializers/carrier_wave.rb
  config/locales/en.yml
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20231124002516_add_photos_to_products.rb
  db/schema.rb
  db/seeds/development.rb
  db/structure.sql
  spec/factories/products.rb
  spec/support/images/product.png
Labels: enhancement

#41 Storefront enhancements
  Gemfile.lock
  app/controllers/storefronts_controller.rb
  app/views/application/_navbar.html.erb
  app/views/storefronts/index.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/seeds/development.rb
  db/structure.sql
  spec/controllers/storefronts_controller_spec.rb
Labels: enhancement
