Repository uiowahjmjohnsonselt2023/selt2023-final-project-team-001, pull requests merged in 2023-12, with the labels that each got.

#48 Fix JavaScript on the checkouts page
  app/assets/javascripts/application.js
  app/javascript/checkouts.js
  app/views/checkouts/index.html.erb
  app/views/layouts/application.html.erb
  config/importmap.rb
  config/initializers/assets.rb
Labels: bug

#46 Add dotenv initializer and example .env file
  .env.example
  .gitignore
  Gemfile
  config/initializers/dotenv.rb
Labels: enhancement

#55 fix: add flash message for using template to update
  app/controllers/storefronts_controller.rb
Labels: bug

#54 Fix error when removing from cart after server restart
  app/assets/config/manifest.js
  app/controllers/checkouts_controller.rb
  app/javascript/checkouts.js
  app/javascript/controllers/checkouts_controller.js
  app/views/checkouts/index.html.erb
  config/importmap.rb
  spec/controllers/checkouts_controller_spec.rb
Labels: bug

#59 fix: can create a product now
  app/controllers/products_controller.rb
Labels: bug

#58 Indicate that footer links don't go anywhere right now
  app/helpers/navbar_helper.rb
  app/views/application/_footer.html.erb
Labels: enhancement

#43 Price alert
  app/controllers/price_alerts_controller.rb
  app/controllers/products_controller.rb
  app/helpers/price_alerts_helper.rb
  app/mailers/price_alert_mailer.rb
  app/models/price_alert.rb
  app/models/product.rb
  app/models/user.rb
  app/views/application/navbar/_user_dropdown.html.erb
  app/views/price_alerts/delete.html.erb
  app/views/price_alerts/edit.html.erb
  app/views/price_alerts/index.html.erb
  app/views/price_alerts/new.html.erb
  app/views/products/listing/_price_alert.html.erb
  app/views/products/show.html.erb
  app/views/profiles/show.html.erb
  config/locales/en.yml
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20231204035349_create_price_alerts.rb
  db/structure.sql
  spec/controllers/price_alerts_controller_spec.rb
  spec/factories/price_alerts.rb
  spec/helpers/price_alerts_helper_spec.rb
  spec/mailers/price_alert_mailer_spec.rb
  spec/requests/price_alerts_spec.rb
  spec/views/price_alerts/send_price_alert.html.erb_spec.rb
Labels: enhancement

#64 tweak: format date and use price instead of price_cents
  app/views/products/history.html.erb
  app/views/products/index.html.erb
Labels: bug, enhancement

#68 fix: choose template flash success
  app/controllers/storefronts_controller.rb
Labels: bug
